% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={STAT 639 - Classification Exercises},
  pdfauthor={Bao Dang},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{STAT 639 - Classification Exercises}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{ISLR Chapter 4: Exercises 1, 4, 8, 14; Chapter 9: Exercise
3(a)-(f)}
\author{Bao Dang}
\date{September 03, 2026}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\newpage

\section{Chapter 4 - Exercise 1}\label{chapter-4---exercise-1}

The logistic regression model can be written as

\[
p(X)=\frac{e^{\beta_0+\beta_1X}}{1+e^{\beta_0+\beta_1X}}.
\]

Let \(\eta=\beta_0+\beta_1X\). Then

\[
p(X)=\frac{e^\eta}{1+e^\eta}.
\]

Multiplying both sides by \(1+e^\eta\),

\[
p(X)(1+e^\eta)=e^\eta.
\]

Therefore,

\[
p(X)=e^\eta(1-p(X)),
\]

so

\[
\frac{p(X)}{1-p(X)}=e^\eta=e^{\beta_0+\beta_1X}.
\]

Taking the natural logarithm gives

\[
\log\left(\frac{p(X)}{1-p(X)}\right)=\beta_0+\beta_1X.
\]

Thus the logistic-function representation and the logit representation
are equivalent.

\section{Chapter 4 - Exercise 4}\label{chapter-4---exercise-4}

This exercise illustrates the \textbf{curse of dimensionality} for local
methods such as KNN.

\subsection{(a) One feature}\label{a-one-feature}

The neighborhood covers 10\% of the range of \(X\). Since \(X\) is
uniformly distributed on \([0,1]\), the expected fraction of
observations in the neighborhood is

\[
0.10 = 10\%.
\]

\subsection{(b) Two features}\label{b-two-features}

An observation must fall within 10\% of the range for both \(X_1\) and
\(X_2\). Therefore the expected fraction is

\[
0.10 \times 0.10 = 0.01 = 1\%.
\]

\subsection{(c) One hundred features}\label{c-one-hundred-features}

For \(p=100\), the expected fraction is

\[
(0.10)^{100}=10^{-100}.
\]

This is essentially zero.

\begin{Shaded}
\begin{Highlighting}[]
\FloatTok{0.1}\SpecialCharTok{\^{}}\DecValTok{100}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1e-100
\end{verbatim}

\subsection{(d) Interpretation}\label{d-interpretation}

As the number of predictors increases, the fraction of observations that
are simultaneously close to a test observation in every dimension
decreases extremely quickly. Therefore, in high dimensions, KNN has very
few genuinely nearby training observations available for prediction. To
obtain enough neighbors, the neighborhood must become much larger, so
the observations are no longer truly local.

\subsection{(e) Hypercube containing 10\% of
observations}\label{e-hypercube-containing-10-of-observations}

If each side of a \(p\)-dimensional hypercube has length \(s\), its
volume is \(s^p\). We want

\[
s^p=0.10,
\]

so

\[
s=0.10^{1/p}.
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{100}\NormalTok{)}
\NormalTok{side\_length }\OtherTok{\textless{}{-}} \FloatTok{0.1}\SpecialCharTok{\^{}}\NormalTok{(}\DecValTok{1} \SpecialCharTok{/}\NormalTok{ p)}
\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{p =}\NormalTok{ p, }\AttributeTok{side\_length =}\NormalTok{ side\_length)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     p side_length
## 1   1   0.1000000
## 2   2   0.3162278
## 3 100   0.9772372
\end{verbatim}

Hence:

\begin{itemize}
\tightlist
\item
  \(p=1\): \(s=0.10\)
\item
  \(p=2\): \(s=\sqrt{0.10}\approx 0.316\)
\item
  \(p=100\): \(s=0.10^{1/100}\approx 0.977\)
\end{itemize}

For 100 predictors, the neighborhood must span about 97.7\% of the range
of \textbf{each} predictor just to contain 10\% of the observations on
average. This shows why the idea of a ``local'' neighborhood breaks down
in high dimensions.

\section{Chapter 4 - Exercise 8}\label{chapter-4---exercise-8}

The logistic regression test error is given directly as \textbf{30\%}.

For 1-nearest neighbors, the training error is 0\% because each training
observation is its own nearest neighbor. Let \(E_{test}\) be the KNN
test error. Because the training and test sets have equal size and the
average error across both sets is 18\%,

\[
\frac{0 + E_{test}}{2}=0.18.
\]

Therefore,

\[
E_{test}=0.36.
\]

So the 1-NN test error is \textbf{36\%}, compared with \textbf{30\%} for
logistic regression. We should prefer \textbf{logistic regression} for
classifying new observations because test-set performance is the
relevant measure of generalization.

\section{Chapter 4 - Exercise 14}\label{chapter-4---exercise-14}

This exercise uses the \texttt{Auto} data from the \texttt{ISLR2}
package.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"ISLR2"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)) \{}
  \FunctionTok{install.packages}\NormalTok{(}\StringTok{"ISLR2"}\NormalTok{)}
\NormalTok{\}}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"MASS"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)) \{}
  \FunctionTok{install.packages}\NormalTok{(}\StringTok{"MASS"}\NormalTok{)}
\NormalTok{\}}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"e1071"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)) \{}
  \FunctionTok{install.packages}\NormalTok{(}\StringTok{"e1071"}\NormalTok{)}
\NormalTok{\}}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"class"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)) \{}
  \FunctionTok{install.packages}\NormalTok{(}\StringTok{"class"}\NormalTok{)}
\NormalTok{\}}

\FunctionTok{library}\NormalTok{(ISLR2)}
\FunctionTok{library}\NormalTok{(MASS)}
\FunctionTok{library}\NormalTok{(e1071)}
\FunctionTok{library}\NormalTok{(class)}

\FunctionTok{data}\NormalTok{(}\StringTok{"Auto"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{\texorpdfstring{(a) Create
\texttt{mpg01}}{(a) Create mpg01}}\label{a-create-mpg01}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mpg\_median }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{(Auto}\SpecialCharTok{$}\NormalTok{mpg)}
\NormalTok{mpg01 }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(Auto}\SpecialCharTok{$}\NormalTok{mpg }\SpecialCharTok{\textgreater{}}\NormalTok{ mpg\_median, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}

\NormalTok{auto }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{mpg01 =} \FunctionTok{factor}\NormalTok{(mpg01), Auto)}

\FunctionTok{table}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg01)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   0   1 
## 196 196
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mpg\_median}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 22.75
\end{verbatim}

\texttt{mpg01\ =\ 1} represents cars with mileage above the sample
median, while \texttt{mpg01\ =\ 0} represents cars at or below the
median.

\subsection{(b) Explore associations}\label{b-explore-associations}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{))}

\FunctionTok{plot}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg01, auto}\SpecialCharTok{$}\NormalTok{cylinders,}
     \AttributeTok{xlab =} \StringTok{"mpg01"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Cylinders"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Cylinders vs mpg01"}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg01, auto}\SpecialCharTok{$}\NormalTok{displacement,}
     \AttributeTok{xlab =} \StringTok{"mpg01"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Displacement"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Displacement vs mpg01"}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg01, auto}\SpecialCharTok{$}\NormalTok{horsepower,}
     \AttributeTok{xlab =} \StringTok{"mpg01"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Horsepower"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Horsepower vs mpg01"}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg01, auto}\SpecialCharTok{$}\NormalTok{weight,}
     \AttributeTok{xlab =} \StringTok{"mpg01"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Weight"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Weight vs mpg01"}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg01, auto}\SpecialCharTok{$}\NormalTok{acceleration,}
     \AttributeTok{xlab =} \StringTok{"mpg01"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Acceleration"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Acceleration vs mpg01"}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg01, auto}\SpecialCharTok{$}\NormalTok{year,}
     \AttributeTok{xlab =} \StringTok{"mpg01"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Model Year"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Year vs mpg01"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{STAT639_HW2_files/STAT639_HW2_files/figure-latex/ch4-ex14b-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

The clearest differences are typically seen for \texttt{cylinders},
\texttt{displacement}, \texttt{horsepower}, and \texttt{weight}:
high-mileage cars tend to have fewer cylinders, smaller displacement,
lower horsepower, and lower weight. \texttt{year} also shows an
association, with newer cars tending to have higher mileage. I will use
\texttt{cylinders}, \texttt{displacement}, \texttt{horsepower}, and
\texttt{weight} as predictors below.

\subsection{(c) Split into training and test
sets}\label{c-split-into-training-and-test-sets}

A reproducible 70/30 random split is used.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{639}\NormalTok{)}

\NormalTok{train\_id }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}
  \FunctionTok{seq\_len}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(auto)),}
  \AttributeTok{size =} \FunctionTok{floor}\NormalTok{(}\FloatTok{0.70} \SpecialCharTok{*} \FunctionTok{nrow}\NormalTok{(auto))}
\NormalTok{)}

\NormalTok{test\_id }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(}\FunctionTok{seq\_len}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(auto)), train\_id)}

\NormalTok{train }\OtherTok{\textless{}{-}}\NormalTok{ auto[train\_id, ]}
\NormalTok{test }\OtherTok{\textless{}{-}}\NormalTok{ auto[test\_id, ]}

\FunctionTok{c}\NormalTok{(}\AttributeTok{training =} \FunctionTok{nrow}\NormalTok{(train), }\AttributeTok{test =} \FunctionTok{nrow}\NormalTok{(test))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## training     test 
##      274      118
\end{verbatim}

\subsection{(d) LDA}\label{d-lda}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lda\_fit }\OtherTok{\textless{}{-}} \FunctionTok{lda}\NormalTok{(}
\NormalTok{  mpg01 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ cylinders }\SpecialCharTok{+}\NormalTok{ displacement }\SpecialCharTok{+}\NormalTok{ horsepower }\SpecialCharTok{+}\NormalTok{ weight,}
  \AttributeTok{data =}\NormalTok{ train}
\NormalTok{)}

\NormalTok{lda\_pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(lda\_fit, }\AttributeTok{newdata =}\NormalTok{ test)}\SpecialCharTok{$}\NormalTok{class}
\NormalTok{lda\_cm }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\AttributeTok{Predicted =}\NormalTok{ lda\_pred, }\AttributeTok{Actual =}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{mpg01)}
\NormalTok{lda\_error }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(lda\_pred }\SpecialCharTok{!=}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{mpg01)}

\NormalTok{lda\_cm}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Actual
## Predicted  0  1
##         0 53  1
##         1 11 53
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lda\_error}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1016949
\end{verbatim}

The LDA test error is 0.1017 (about 10.2\%).

\subsection{(e) QDA}\label{e-qda}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{qda\_fit }\OtherTok{\textless{}{-}} \FunctionTok{qda}\NormalTok{(}
\NormalTok{  mpg01 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ cylinders }\SpecialCharTok{+}\NormalTok{ displacement }\SpecialCharTok{+}\NormalTok{ horsepower }\SpecialCharTok{+}\NormalTok{ weight,}
  \AttributeTok{data =}\NormalTok{ train}
\NormalTok{)}

\NormalTok{qda\_pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(qda\_fit, }\AttributeTok{newdata =}\NormalTok{ test)}\SpecialCharTok{$}\NormalTok{class}
\NormalTok{qda\_cm }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\AttributeTok{Predicted =}\NormalTok{ qda\_pred, }\AttributeTok{Actual =}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{mpg01)}
\NormalTok{qda\_error }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(qda\_pred }\SpecialCharTok{!=}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{mpg01)}

\NormalTok{qda\_cm}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Actual
## Predicted  0  1
##         0 55  2
##         1  9 52
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{qda\_error}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.09322034
\end{verbatim}

The QDA test error is 0.0932 (about 9.3\%).

\subsection{(f) Logistic regression}\label{f-logistic-regression}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{logit\_fit }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}
\NormalTok{  mpg01 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ cylinders }\SpecialCharTok{+}\NormalTok{ displacement }\SpecialCharTok{+}\NormalTok{ horsepower }\SpecialCharTok{+}\NormalTok{ weight,}
  \AttributeTok{data =}\NormalTok{ train,}
  \AttributeTok{family =}\NormalTok{ binomial}
\NormalTok{)}

\NormalTok{logit\_prob }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(logit\_fit, }\AttributeTok{newdata =}\NormalTok{ test, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{logit\_pred }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(logit\_prob }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{), }\AttributeTok{levels =} \FunctionTok{levels}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{mpg01))}

\NormalTok{logit\_cm }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\AttributeTok{Predicted =}\NormalTok{ logit\_pred, }\AttributeTok{Actual =}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{mpg01)}
\NormalTok{logit\_error }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(logit\_pred }\SpecialCharTok{!=}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{mpg01)}

\NormalTok{logit\_cm}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Actual
## Predicted  0  1
##         0 53  1
##         1 11 53
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{logit\_error}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1016949
\end{verbatim}

The logistic-regression test error is 0.1017 (about 10.2\%).

\subsection{(g) Naive Bayes}\label{g-naive-bayes}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nb\_fit }\OtherTok{\textless{}{-}} \FunctionTok{naiveBayes}\NormalTok{(}
\NormalTok{  mpg01 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ cylinders }\SpecialCharTok{+}\NormalTok{ displacement }\SpecialCharTok{+}\NormalTok{ horsepower }\SpecialCharTok{+}\NormalTok{ weight,}
  \AttributeTok{data =}\NormalTok{ train}
\NormalTok{)}

\NormalTok{nb\_pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(nb\_fit, }\AttributeTok{newdata =}\NormalTok{ test)}
\NormalTok{nb\_cm }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\AttributeTok{Predicted =}\NormalTok{ nb\_pred, }\AttributeTok{Actual =}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{mpg01)}
\NormalTok{nb\_error }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(nb\_pred }\SpecialCharTok{!=}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{mpg01)}

\NormalTok{nb\_cm}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Actual
## Predicted  0  1
##         0 53  1
##         1 11 53
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nb\_error}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1016949
\end{verbatim}

The naive-Bayes test error is 0.1017 (about 10.2\%).

\subsection{(h) KNN for several values of
K}\label{h-knn-for-several-values-of-k}

KNN is distance-based, so the predictors are standardized using the
\textbf{training-set} means and standard deviations. The same
transformation is then applied to the test set.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{vars }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"cylinders"}\NormalTok{, }\StringTok{"displacement"}\NormalTok{, }\StringTok{"horsepower"}\NormalTok{, }\StringTok{"weight"}\NormalTok{)}

\NormalTok{x\_train }\OtherTok{\textless{}{-}}\NormalTok{ train[, vars]}
\NormalTok{x\_test }\OtherTok{\textless{}{-}}\NormalTok{ test[, vars]}

\NormalTok{train\_mean }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(x\_train, mean)}
\NormalTok{train\_sd }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(x\_train, sd)}

\NormalTok{x\_train\_scaled }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(x\_train, }\AttributeTok{center =}\NormalTok{ train\_mean, }\AttributeTok{scale =}\NormalTok{ train\_sd)}
\NormalTok{x\_test\_scaled }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(x\_test, }\AttributeTok{center =}\NormalTok{ train\_mean, }\AttributeTok{scale =}\NormalTok{ train\_sd)}

\NormalTok{k\_values }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{9}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{25}\NormalTok{)}

\NormalTok{knn\_errors }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(k\_values, }\ControlFlowTok{function}\NormalTok{(k) \{}
\NormalTok{  pred }\OtherTok{\textless{}{-}} \FunctionTok{knn}\NormalTok{(}
    \AttributeTok{train =}\NormalTok{ x\_train\_scaled,}
    \AttributeTok{test =}\NormalTok{ x\_test\_scaled,}
    \AttributeTok{cl =}\NormalTok{ train}\SpecialCharTok{$}\NormalTok{mpg01,}
    \AttributeTok{k =}\NormalTok{ k}
\NormalTok{  )}
  \FunctionTok{mean}\NormalTok{(pred }\SpecialCharTok{!=}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{mpg01)}
\NormalTok{\})}

\NormalTok{knn\_results }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{K =}\NormalTok{ k\_values,}
  \AttributeTok{Test\_Error =}\NormalTok{ knn\_errors}
\NormalTok{)}

\NormalTok{knn\_results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    K Test_Error
## 1  1 0.05084746
## 2  3 0.08474576
## 3  5 0.08474576
## 4  7 0.09322034
## 5  9 0.09322034
## 6 15 0.09322034
## 7 25 0.09322034
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{best\_knn }\OtherTok{\textless{}{-}}\NormalTok{ knn\_results[}\FunctionTok{which.min}\NormalTok{(knn\_results}\SpecialCharTok{$}\NormalTok{Test\_Error), ]}
\NormalTok{best\_knn}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   K Test_Error
## 1 1 0.05084746
\end{verbatim}

For this split, the best tested value is \(K=1\), with test error 0.0508
(about 5.1\%).

\subsubsection{Model comparison}\label{model-comparison}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_results }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Method =} \FunctionTok{c}\NormalTok{(}\StringTok{"LDA"}\NormalTok{, }\StringTok{"QDA"}\NormalTok{, }\StringTok{"Logistic Regression"}\NormalTok{, }\StringTok{"Naive Bayes"}\NormalTok{, }\FunctionTok{paste0}\NormalTok{(}\StringTok{"KNN (K="}\NormalTok{, best\_knn}\SpecialCharTok{$}\NormalTok{K, }\StringTok{")"}\NormalTok{)),}
  \AttributeTok{Test\_Error =} \FunctionTok{c}\NormalTok{(lda\_error, qda\_error, logit\_error, nb\_error, best\_knn}\SpecialCharTok{$}\NormalTok{Test\_Error)}
\NormalTok{)}

\NormalTok{model\_results[}\FunctionTok{order}\NormalTok{(model\_results}\SpecialCharTok{$}\NormalTok{Test\_Error), ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                Method Test_Error
## 5           KNN (K=1) 0.05084746
## 2                 QDA 0.09322034
## 1                 LDA 0.10169492
## 3 Logistic Regression 0.10169492
## 4         Naive Bayes 0.10169492
\end{verbatim}

The methods all use the same training/test split, so their test errors
can be compared directly. The method at the top of the table has the
lowest test error for this particular split.

\section{Chapter 9 - Exercise 3}\label{chapter-9---exercise-3}

We have seven observations in two dimensions.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{svm\_data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{X1 =} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{4}\NormalTok{),}
  \AttributeTok{X2 =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{1}\NormalTok{),}
  \AttributeTok{Class =} \FunctionTok{factor}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Red"}\NormalTok{, }\StringTok{"Red"}\NormalTok{, }\StringTok{"Red"}\NormalTok{, }\StringTok{"Red"}\NormalTok{, }\StringTok{"Blue"}\NormalTok{, }\StringTok{"Blue"}\NormalTok{, }\StringTok{"Blue"}\NormalTok{)),}
  \AttributeTok{Obs =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{7}
\NormalTok{)}

\NormalTok{svm\_data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   X1 X2 Class Obs
## 1  3  4   Red   1
## 2  2  2   Red   2
## 3  4  4   Red   3
## 4  1  4   Red   4
## 5  2  1  Blue   5
## 6  4  3  Blue   6
## 7  4  1  Blue   7
\end{verbatim}

\subsection{(a) Sketch the
observations}\label{a-sketch-the-observations}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Class == "Red"  → pch = 19 → ● filled circle}
\CommentTok{\# Class == "Blue" → pch = 17 → ▲ filled triangle}

\FunctionTok{plot}\NormalTok{(}
\NormalTok{  svm\_data}\SpecialCharTok{$}\NormalTok{X1,}
\NormalTok{  svm\_data}\SpecialCharTok{$}\NormalTok{X2,}
  \AttributeTok{pch =} \FunctionTok{ifelse}\NormalTok{(svm\_data}\SpecialCharTok{$}\NormalTok{Class }\SpecialCharTok{==} \StringTok{"Red"}\NormalTok{, }\DecValTok{19}\NormalTok{, }\DecValTok{17}\NormalTok{),}
  \AttributeTok{xlab =} \FunctionTok{expression}\NormalTok{(X[}\DecValTok{1}\NormalTok{]),}
  \AttributeTok{ylab =} \FunctionTok{expression}\NormalTok{(X[}\DecValTok{2}\NormalTok{]),}
  \AttributeTok{main =} \StringTok{"Chapter 9, Exercise 3"}
\NormalTok{)}
\FunctionTok{text}\NormalTok{(svm\_data}\SpecialCharTok{$}\NormalTok{X1, svm\_data}\SpecialCharTok{$}\NormalTok{X2, }\AttributeTok{labels =}\NormalTok{ svm\_data}\SpecialCharTok{$}\NormalTok{Obs, }\AttributeTok{pos =} \DecValTok{3}\NormalTok{)}
\FunctionTok{legend}\NormalTok{(}\StringTok{"topleft"}\NormalTok{, }\AttributeTok{legend =} \FunctionTok{c}\NormalTok{(}\StringTok{"Red"}\NormalTok{, }\StringTok{"Blue"}\NormalTok{), }\AttributeTok{pch =} \FunctionTok{c}\NormalTok{(}\DecValTok{19}\NormalTok{, }\DecValTok{17}\NormalTok{), }\AttributeTok{bty =} \StringTok{"n"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{STAT639_HW2_files/STAT639_HW2_files/figure-latex/ch9-ex3a-1.pdf}}

\subsection{(b) Optimal separating
hyperplane}\label{b-optimal-separating-hyperplane}

A convenient form of the maximal-margin hyperplane is

\[
X_1-X_2=0.5,
\]

or equivalently

\[
0.5-X_1+X_2=0.
\]

The nearest red observations satisfy \(X_1-X_2=0\), while the nearest
blue observations satisfy \(X_1-X_2=1\). The maximal-margin boundary
lies halfway between these two parallel lines.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}
\NormalTok{  svm\_data}\SpecialCharTok{$}\NormalTok{X1,}
\NormalTok{  svm\_data}\SpecialCharTok{$}\NormalTok{X2,}
  \AttributeTok{pch =} \FunctionTok{ifelse}\NormalTok{(svm\_data}\SpecialCharTok{$}\NormalTok{Class }\SpecialCharTok{==} \StringTok{"Red"}\NormalTok{, }\DecValTok{19}\NormalTok{, }\DecValTok{17}\NormalTok{),}
  \AttributeTok{xlab =} \FunctionTok{expression}\NormalTok{(X[}\DecValTok{1}\NormalTok{]),}
  \AttributeTok{ylab =} \FunctionTok{expression}\NormalTok{(X[}\DecValTok{2}\NormalTok{]),}
  \AttributeTok{main =} \StringTok{"Maximal{-}Margin Hyperplane"}
\NormalTok{)}
\FunctionTok{text}\NormalTok{(svm\_data}\SpecialCharTok{$}\NormalTok{X1, svm\_data}\SpecialCharTok{$}\NormalTok{X2, }\AttributeTok{labels =}\NormalTok{ svm\_data}\SpecialCharTok{$}\NormalTok{Obs, }\AttributeTok{pos =} \DecValTok{3}\NormalTok{)}

\CommentTok{\# X1 {-} X2 = 0.5  {-}\textgreater{}  X2 = X1 {-} 0.5}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{a =} \SpecialCharTok{{-}}\FloatTok{0.5}\NormalTok{, }\AttributeTok{b =} \DecValTok{1}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{STAT639_HW2_files/STAT639_HW2_files/figure-latex/ch9-ex3b-1.pdf}}

\subsection{(c) Classification rule}\label{c-classification-rule}

Using

\[
\beta_0=0.5,\qquad \beta_1=-1,\qquad \beta_2=1,
\]

the classifier is

\[
0.5-X_1+X_2=0.
\]

Therefore:

\begin{itemize}
\tightlist
\item
  classify an observation as \textbf{Red} if \(0.5-X_1+X_2>0\);
\item
  classify it as \textbf{Blue} otherwise.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{score }\OtherTok{\textless{}{-}} \FloatTok{0.5} \SpecialCharTok{{-}}\NormalTok{ svm\_data}\SpecialCharTok{$}\NormalTok{X1 }\SpecialCharTok{+}\NormalTok{ svm\_data}\SpecialCharTok{$}\NormalTok{X2}
\NormalTok{predicted }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(score }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, }\StringTok{"Red"}\NormalTok{, }\StringTok{"Blue"}\NormalTok{)}
\FunctionTok{data.frame}\NormalTok{(svm\_data, }\AttributeTok{score =}\NormalTok{ score, }\AttributeTok{predicted =}\NormalTok{ predicted)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   X1 X2 Class Obs score predicted
## 1  3  4   Red   1   1.5       Red
## 2  2  2   Red   2   0.5       Red
## 3  4  4   Red   3   0.5       Red
## 4  1  4   Red   4   3.5       Red
## 5  2  1  Blue   5  -0.5      Blue
## 6  4  3  Blue   6  -0.5      Blue
## 7  4  1  Blue   7  -2.5      Blue
\end{verbatim}

\subsection{(d) Margin}\label{d-margin}

The two margin boundaries are

\[
X_1-X_2=0
\]

and

\[
X_1-X_2=1.
\]

The separating hyperplane \(X_1-X_2=0.5\) lies exactly halfway between
them.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}
\NormalTok{  svm\_data}\SpecialCharTok{$}\NormalTok{X1,}
\NormalTok{  svm\_data}\SpecialCharTok{$}\NormalTok{X2,}
  \AttributeTok{pch =} \FunctionTok{ifelse}\NormalTok{(svm\_data}\SpecialCharTok{$}\NormalTok{Class }\SpecialCharTok{==} \StringTok{"Red"}\NormalTok{, }\DecValTok{19}\NormalTok{, }\DecValTok{17}\NormalTok{),}
  \AttributeTok{xlab =} \FunctionTok{expression}\NormalTok{(X[}\DecValTok{1}\NormalTok{]),}
  \AttributeTok{ylab =} \FunctionTok{expression}\NormalTok{(X[}\DecValTok{2}\NormalTok{]),}
  \AttributeTok{main =} \StringTok{"Maximal{-}Margin Classifier and Margins"}
\NormalTok{)}
\FunctionTok{text}\NormalTok{(svm\_data}\SpecialCharTok{$}\NormalTok{X1, svm\_data}\SpecialCharTok{$}\NormalTok{X2, }\AttributeTok{labels =}\NormalTok{ svm\_data}\SpecialCharTok{$}\NormalTok{Obs, }\AttributeTok{pos =} \DecValTok{3}\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{a =} \SpecialCharTok{{-}}\FloatTok{0.5}\NormalTok{, }\AttributeTok{b =} \DecValTok{1}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)  }\CommentTok{\# decision boundary}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{a =} \DecValTok{0}\NormalTok{, }\AttributeTok{b =} \DecValTok{1}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)     }\CommentTok{\# red margin: X2 = X1}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{a =} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\AttributeTok{b =} \DecValTok{1}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)    }\CommentTok{\# blue margin: X2 = X1 {-} 1}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{STAT639_HW2_files/STAT639_HW2_files/figure-latex/ch9-ex3d-1.pdf}}

\subsection{(e) Support vectors}\label{e-support-vectors}

The support vectors are the observations lying on the two margin
boundaries:

\begin{itemize}
\tightlist
\item
  Red: observations \textbf{2} and \textbf{3}, where \(X_1-X_2=0\)
\item
  Blue: observations \textbf{5} and \textbf{6}, where \(X_1-X_2=1\)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{svm\_data[}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{), ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   X1 X2 Class Obs
## 2  2  2   Red   2
## 3  4  4   Red   3
## 5  2  1  Blue   5
## 6  4  3  Blue   6
\end{verbatim}

\subsection{(f) Moving observation 7
slightly}\label{f-moving-observation-7-slightly}

Observation 7 is \((4,1)\), so

\[
X_1-X_2=3.
\]

It lies well inside the Blue side and is not a support vector. The
maximal-margin hyperplane is determined by the observations closest to
the boundary, namely observations 2, 3, 5, and 6. Therefore, a
\textbf{small movement} of observation 7 that leaves it away from the
margin will not change the maximal-margin hyperplane.

\end{document}
